framework:
    messenger:
        default_bus: messenger.bus.default

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        messages: ~

        routing:
            'App\Message\SendWeatherReminderMessage': async
